---

- name: Minecraft service is stopped
  systemd:
    state: stopped
    name: minecraft
    enabled: yes
    daemon_reload: yes
  ignore_errors: yes
  tags:
    - always

- include: configure.yml
  tags:
    - install
    - restore
    - config

- include: restore.yml
  tags:
    - restore

- include: install.yml
  tags:
    - install
    - restore
    - update

- include: plugins.yml
  tags:
    - install
    - update
    - plugins

- include: backup.yml
  tags:
    - backup

- name: Minecraft service is running
  become: yes
  systemd:
    state: started
    name: minecraft
    enabled: yes
    daemon_reload: yes
  tags:
    - always